### ISSUE TITLE
Fit multiple time series

### ISSUE THREAD

**Issue by BlackEdder** [kingaa/pomp#10]
This is not really an issue, but more a request for some pointers. All the examples I found deal with the situation were you have one long time series. In contrast I have a large number of short time series. Is it possible to fit data such as that to a model? The data model does not seem to allow one to pass multiple time series. (The time series are independent of each other, but of course dependent within the time series).

**Comment by kingaa** [comment]
Your question can be answered on at least two levels.  On the formal level, pomp can certainly accommodate multivariate time series.  There is one example of this in the documentation (ou2), and we have used this capacity several times in our own research.  Formally speaking, there is nothing to stop you treating all your time series at once.

On the practical level, however, when the number of time series is large, the methods pomp implements at the moment are not efficient.  The problem is exacerbated when there are strong dependencies among the different series.  The case you describe, of a large number of independent time series, is an interesting one that has recently been grabbing our attention as well.  

Three ways of approaching the problem stand out.  If you are willing to allow each unit its own parameters, the problem is one of many pomps that can be treated independently.  I suppose this has already occurred to you and that the reason for your question is that some parameters are common to all the units and you want to pool the data to make inferences about them.  To deal with this case, my colleague Ed Ionides has adapted the iterated filtering algorithm to make maximum likelihood inference possible.  [Here is a link to the paper](http://dx.doi.org/10.1093/aje/kwv044) and [another link to a tutorial on the subject](http://kingaa.github.io/sbied/contacts/contacts.html) from our course at [SISMID](http://sismid.uw.edu/).  We are currently working on extending pomp to deal with this case in a more systematic and thorough fashion with a more robust interface.  Finally, I can imagine you might want to deal with random effects, which in some ways is a special case of the second approach.  This case is examined, in an application, in the materials I just mentioned.

Does this help?

**Comment by BlackEdder** [comment]
Thank you for the thorough answer. The example seems to be exactly what I want, so I will have a careful look at it.

**Comment by kingaa** [comment]
See also the new [FAQ 3.2](https://kingaa.github.io/pomp/FAQ.html#multivariate-data-pomp).
