### ISSUE TITLE
Summarizing the posterior distribution

### ISSUE THREAD

**Issue by tpa8395** [kingaa/pomp#14]
When using pmcmc for estimation, I note that the package outputs parameter estimates which can be extracted using the coef function. Does the software calculate these estimates using all pmcmc samples in a chain? Is there a way to specify burn-in? Does the package calculate standard deviations or credible intervals for parameters?

**Comment by kingaa** [comment]
When applied to the result of a `pmcmc` calculation, `coef` returns the current (final) state of the chain and so is not so useful for inference purposes.  Using `conv.rec`, you can extract an `mcmc` object (defined in package **coda**) containing the full history of the MCMC chain .  This can be windowed, thinned, etc., like any other **coda** `mcmc` object.  Given such an object, **coda** also provides a number of methods for diagnosing convergence, mixing, etc. and for extracting credible intervals, posterior medians, etc.

Note too that a set of PMCMC chains can be combined into an object of class `pmcmcList` using the `c` operator: `conv.rec` applied to such an object returns a `coda::mcmc.list` object, with some additional diagnostic methods available.

Examples of this are provided on the [pmcmc help page](https://www.rdocumentation.org/packages/pomp/topics/Particle%20Markov%20Chain%20Monte%20Carlo), in the [Getting Started vignette](http://kingaa.github.io/pomp/vignettes/getting_started.html#sampling-the-posterior-using-particle-markov-chain-monte-carlo), and in the [JSS paper](http://kingaa.github.io/pomp/vignettes/pompjss.pdf#nameddest=subsection.4.4).

Because this isn't as clearly documented in the help pages, I consider this a documentation bug.  I will edit those pages in the next few days.  **Please be so kind as to have a look at the new documentation when it comes out and let me know if you have specific suggestions or otherwise see room for improvement in either the documentation or the codes.**

**Comment by tpa8395** [comment]
Thanks for your timely and clear response. I will look at the new documentation and provide some feedback.

**Comment by kingaa** [comment]
Please have a look at the documentation in version 1.3.4.1.  Any suggestions for improvements would be appreciated!
