### ISSUE TITLE
How to generate random normal variable in the C snippets

### ISSUE THREAD

**Issue by ghost** [kingaa/pomp#24]
Hi, I am new in programming in R using C code. I want to generate random normal variable in the C snippets in the pomp, former I could define my own generating function in C as:

```
#include  < math.h >
#include  < stdlib.h >

double
randn (double mu, double sigma)
{
  double U1, U2, W, mult;
  static double X1, X2;
  static int call = 0;

  if (call == 1)
    {
      call = !call;
      return (mu + sigma * (double) X2);
    }

  do
    {
      U1 = -1 + ((double) rand () / RAND_MAX) * 2;
      U2 = -1 + ((double) rand () / RAND_MAX) * 2;
      W = pow (U1, 2) + pow (U2, 2);
    }
  while (W >= 1 || W == 0);

  mult = sqrt ((-2 * log (W)) / W);
  X1 = U1 * mult;
  X2 = U2 * mult;

  call = !call;

  return (mu + sigma * (double) X1);
}
```

How could I do this in the pomp, what I want is 

```
sir.step<-"
double rate[2];
double dN[2];
double P=S+I+R;
rate[0]=bet*I/P;
rate[1]=mu;
reulermultinom(1,S,&rate[0],dt,&dN[0]);
reulermultinom(1,I,&rate[1],dt,&dN[1]);
if(!R_FINITE(S)) Rprintf(\"%lg %lg %lg %lg %lg %lg %lg %lg %lg\\n\",dN[0],rate[0],dN[1],rate[1],bet,mu,S,I,R);
S+=-dN[0];
I+=dN[0]-dN[1];
R+=dN[1];
"

sir<-pomp(data=data.frame(cases=data,time=seq(1,14,by=1)),
          times="time",t0=0,dmeasure=Csnippet(dmeas),
          rmeasure=Csnippet(rmeas),rprocess=euler.sim(
            step.fun=Csnippet(sir.step),delta.t=1/14/2),
          statenames=c("S","I","R"),
          paramnames=c("bet","mu","rho","theta1","theta2"),
          initializer=function(params,t0,...){
            ps<-exp(params["theta1"])/(1+exp(params["theta1"])+exp(params["theta2"]))
            pi<-1/(1+exp(params["theta1"])+exp(params["theta2"]))
            pr<-exp(params["theta2"])/(1+exp(params["theta1"])+exp(params["theta2"]))
            return(setNames(as.numeric(rmultinom(1,763,prob=c(ps,pi,1-ps-pi))),
                     c("S","I","R")))
          },params=c(bet=2,mu=0.5,rho=3,theta1=5,theta2=1))
```

I want to generate random normal variable in the sir.step function, how could I include < math.h >,  < stdlib.h > the two header? Or you know some better way to generate random variable in the pomp? Thank you in advance.

**Comment by kingaa** [comment]
**R**, being a statistical programming environment, is helpfully packed with lots of knowledge about probability distributions.  In particular, it has very accurate and efficient codes for computing with the most common standard distributions, including the normal distribution.  In an **R** session, do 

```
?rnorm
```

to learn about the built-in facilities for the normal distribution.

In **pomp**, since it's an **R** package, you have access to all this.  In particular, for your C snippets, you have access to **R**'s underlying C codes.  This is documented in the [**R** extensions manual](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Distribution-functions), which is linked to i at several points in **pomp**'s documentation.

So the short answers are: 
- There is no need to implement your own normal distribution codes. 
- You need not include any stdlib headers.  
- You can simply call `rnorm` in your C snippet and it will be there for you.

**Comment by christelpei** [comment]
I have a question that points in a similar direction: what do I do if I would like to include a distribution that is not in the R extensions? 
I would like to use the Poisson Binomial Distribution as implemented in the R package poibin which I have installed and which is available in my R session. Apparently, I cannot use it in the Csnippet as described above. Is there a way to also use this code within a Csnippet or do I have to include C-code or libraries (if available)?

**Comment by kingaa** [comment]
@christelpei:

Good question.  On general grounds, it is clear that you must either (1) link to the library in the other package (in your case **poibin**) or (2) take advantage of the open-source nature of **poibin**, copying the package's source code into your own.  The latter is probably preferable in this case, since **poibin** does not appear to be a particularly complicated package.  I don't know how to follow option (1) and suspect that it may not even be possible.

To follow option (2), you can pass the package source code as the `globals` argument of `pomp` to accomplish this.  Perhaps a future release of **pomp** should allow one to link against statically compiled libraries.  With such a facility, you would still have to take the package source code and compile it, but you wouldn't have to copy it into your codes.

**Comment by christelpei** [comment]
Trying to follow option (2), I have downloaded the package source into my working directory and tried both
`pomp(inc_b,times="year",t0=1990,..., globals = './poibin/R/funs.R')
) -> sir`
`pomp(inc_b,times="year",t0=1990,..., globals = "./poibin/R/funs.R")
) -> sir`
which did not really work (neither pasting the code instead of the file name).
From the reference manual I also suspect that I rather would have to provide C code instead of R code but I cannot really make sense out of the error messages. Therefore, I would be glad to get more information on how to feed the functions into the pomp object, i.e. which format to use.

**Comment by kingaa** [comment]
Those lines of yours will just include the literal line `./poibin/R/funs.R` into the C code.  As you surmise, you need to provide C code, not R code.  Moreover, you'll need to provide actual code, not merely a filename.

[As an informative exercise, try setting the `cdir` and `cfile` options in your call to `pomp`.  This will cause the C codes to be written in the file of your choice.  You can then examine those codes and directly observe the effect of your experiments.]

Since the developer of **poibin** has not provided a C API for his users (which is not generally expected of package developers), you'll have to hack one yourself.  Looking at the source code for the **poibin** functions you want, it appears it would not be terribly difficult to reverse-engineer them in C:  each does a bit of lightweight computation and then calls a C function.  The C function is defined in a single file in the package's `src` directory.

I'd recommend translating the `rpoibin` or `dpoibin` function, as needed, into C (perhaps using Rcpp if that makes life easier).  You can cut and paste the **poibin** `src` file into your code and include the whole thing, verbatim, as the argument to `globals`.

**Comment by christelpei** [comment]
Well, probably discussing and rethinking the problem along the way had the most educational side effects. For my purposes a sum of Poisson distributions (with different means) will do the job comparably well and much easier (and probably much faster). Still, it is good to know how to include other code in the future! Thanks for both!
