### ISSUE TITLE
Can I convert a named vector or list with random-walk perturbations to rw.sd function?

### ISSUE THREAD

**Issue by Jochen2222** [kingaa/pomp#33]
Hi,
I'm trying to estimate parameters using mif2. Due to an update (I guess) you need to specify random-walk perturbations with the rw.sd function. Before, a named vector worked fine.
My question is if there is a way to convert a named vector to the rw.sd function since my model has got too many parameters to write them all down individually like rw.sd (a=0.01, b=0.01,...)?
Thanks
Jochen

**Comment by kingaa** [comment]
How about the following, where `x` is your named vector?
```
x <- do.call(rw.sd,as.list(x))
```
`x` is now in a format acceptable to `mif2`.

How have you been treating initial value parameters?

**Comment by Jochen2222** [comment]
Thanks for your quick response. Your suggestion works fine.
The initial value parameters are pooled in a named vector which seems to work in mif2.
Thanks a lot for your help!

**Comment by kingaa** [comment]
Hmm, I worry about what "seems to work" might actually mean.  You might want to check that those initial value parameters are really being treated as such, i.e., that they are only being perturbed at the appropriate times.

BTW, it is possible to pass the `rw.sd` as a matrix, which may be better for your purposes.  This should be an `npar` x `ntimes` matrix with rownames, where the `(i,j)`-th entry represents the s.d. of the (normal) perturbation to be applied to parameter `i` before advancing the state from time `t[j-1]` to time `t[j]`.

**Comment by Spatial-R** [comment]
In my opinion, `x <- do.call(rw.sd,as.list(x))` to define the value of rw.sd may be unsuitable because this setting can not work on the initial parameter value which only need the random walk at the first time-point(ivp).
In my situation,  a function to do the MIF2 with the paramnames in pomp varied by the analysis purposes was created. I follow your step to create a matrix which is npar x ntimes with rownames, but how can i pass it to the value of the rw.sd augment?
