### ISSUE TITLE
Warning: "in 'table_lookup': extrapolating at ..."

### ISSUE THREAD

**Issue by tomessilva** [kingaa/pomp#46]
First of all, thanks for maintaining such useful package. My experience with it has been positive, and the quantity and quality of documentation is quite good.

I have a question, though: when running trajectory matching, I'm always getting these specific warnings which are somewhat descriptive (i.e. i understand what's wrong), but a bit mysterious as well (i.e. i don't understand why it's happening).

For example, with a model with data/observables and covariates defined from t = 0 to t = 127 (with t0=0, on the call to the pomp() function), I get these warnings:

>1: in 'table_lookup': extrapolating at 1.288334e+02
>2: in 'table_lookup': extrapolating at 1.288334e+02
>3: in 'table_lookup': extrapolating at 1.311213e+02
>4: in 'table_lookup': extrapolating at 1.311213e+02
>5: in 'table_lookup': extrapolating at 1.305028e+02
>6: in 'table_lookup': extrapolating at 1.305028e+02
>[...]

My interpretation of these warnings is that the code is trying to get data/observables or covariates for t > 127, and they are undefined at those points:

>21 records of 4 observables, recorded from t = 0 to 127
>zero time, t0 = 0
>42 records of 16 covariates, recorded from t = 0 to 127

Is there an obvious reason why this behaviour (i.e. code trying to extrapolate outside the implicit time period defined by the observables+covariates) would occur? (perhaps I forgot to set up something?)

Should I be worried about these warnings? (it seems to me that the trajectory matching is working correctly otherwise, despite these warnings)

Once again, thanks for your work.

(If anything is required to better understand the source of the warnings [code, data, running diagnostic functions], please let me know.)

**Comment by kingaa** [comment]
**pomp** incorporates time-varying covariates via a lookup table.  Whenever your model needs the value of a covariate at a particular time, it uses the lookup table provided (via the `covar` and `tcovar` options of `pomp`), linearly interpolating if necessary.  It can happen that the required computation depends on values of the covariates *outside* the time interval covered by the lookup table.  When this happens, **pomp** does linear extrapolation, with a warning.

This can be a problem if the linear extrapolation is not accurate.  To avoid this, be sure to give values for the covariates over a time interval that covers the full range of relevant times, i.e., `t0` to the time of the last observation.

Note that the ODE integration algorithms underlying `trajectory` can sometimes evaluate the covariates beyond the last observation time.  To avoid warnings (and the potential inaccuracy they signal) in this case, it may be necessary to supply values for the covariates somewhat beyond the final observation time.

Thanks for bringing this issue up.  It should have long since been in the FAQ, and now it will be.  Please help me polish up the FAQ by helping me clarify the above.

**Comment by tomessilva** [comment]
>pomp incorporates time-varying covariates via a lookup table. Whenever your model needs the value of a covariate at a particular time, it uses the lookup table provided (via the covar and tcovar options of pomp), linearly interpolating if necessary. It can happen that the required computation depends on values of the covariates outside the time interval covered by the lookup table. When this happens, pomp does linear extrapolation, with a warning.

Yes, this part was clear from the documentation and the warning messages themselves.

>This can be a problem if the linear extrapolation is not accurate. To avoid this, be sure to give values for the covariates over a time interval that covers the full range of relevant times, i.e., t0 to the time of the last observation.

I think I did things correctly here (covariates are defined, with no missing values, from the `t0` [t=0] to the time of the last observation [t=127]). I do have missing values in the observables, but I think those are being dealt with correctly (and those occur, obviously, within the period from `t0` to the time of the final observation, so they shouldn't be the source of these warnings).

>Note that the ODE integration algorithms underlying trajectory can sometimes evaluate the covariates beyond the last observation time. To avoid warnings (and the potential inaccuracy they signal) in this case, it may be necessary to supply values for the covariates somewhat beyond the final observation time.

Your explanation seems like the most plausible one and, in a practical sense, the suggestion you provide is probably the easiest way to deal with the issue. In my case, the covariates are more or less locally constant, so I duplicated the t=127 row of covariates and set it to t=150 (so the extrapolation is constant) and... yes, the warnings went away.

Thanks for your help and clarifications.

**Comment by kingaa** [comment]
This is now [FAQ 4.5](http://kingaa.github.io/pomp/FAQ.html#extrapolation-warnings).
