### ISSUE TITLE
statenames error with R version 3.2.2

### ISSUE THREAD

**Issue by dtsh2** [kingaa/pomp#7]
I get the following error message using the R 3.2.2 version, but not the R 3.0.3 version:

"Error in paste(statenames, ".0", sep = "") : argument "statenames" is missing, with no default
Error: ‘simulate’ error"

Attached is the relevant section of R code (r_code.txt) and the C code. I tried to load up the .R and .c files but got an 'Unfortunately, we don’t support that file type.' message when I tried to load them. The relevant R code to generate the .dll file from the c code is included.

[r_code.txt](https://github.com/kingaa/pomp/files/38696/r_code.txt)
[lbvseirNoSeasFreqTwoParsMeasureBinom.txt](https://github.com/kingaa/pomp/files/38697/lbvseirNoSeasFreqTwoParsMeasureBinom.txt)

**Comment by kingaa** [comment]
Thanks for bringing this to my attention.  As it stands, I can't quite see what the problem might be, because I can't get the codes to compile.  When I do

```
R CMD SHLIB lbv.c
```

(having renamed your C source file), I get

```
lbv.c: In function ‘sir_euler_simulator’:
lbv.c:107:14: error: ‘KAPPA’ undeclared (first use in this function)
lbv.c:107:14: note: each undeclared identifier is reported only once for each function it appears in
lbv.c:108:13: error: ‘PSI’ undeclared (first use in this function)
lbv.c:109:13: error: ‘DELTA’ undeclared (first use in this function)
lbv.c:109:22: error: ‘K’ undeclared (first use in this function)
lbv.c:120:14: error: ‘SIGMA’ undeclared (first use in this function)
lbv.c:122:14: error: ‘TAU’ undeclared (first use in this function)
lbv.c:124:14: error: ‘ALPHA’ undeclared (first use in this function)
lbv.c:127:14: error: ‘MU’ undeclared (first use in this function)
```

Have you checked to see if this file compiles on your system?

Also, when I do

```
source("lbv.R")
```

(having renamed your R code file), I get

```
Error in source("lbv.R") : lbv.R:56:0: unexpected end of input
54:         }
55:     ) -> lbvdat
```

Which is a syntax error.  I notice that I wouldn't be able to run it even without the syntax error, lacking a data file.  Don't feel obliged to send me your data, but some fake data of the same size and shape would allow me to run the code and diagnose the problem.

**Comment by dtsh2** [comment]
Aaron, I shall email you the .dll code.

**Comment by dtsh2** [comment]
I hope these help!

**Comment by dtsh2** [comment]
I just emailed the .c, .dll, data, and .R code. Hopefully that does the job.

**Comment by kingaa** [comment]
I don't think the DLL you sent can possibly correspond to the C code, because the latter won't compile.  When you switched to R 3.2.2 and the new version of pomp, did you recompile the DLL?

**Comment by dtsh2** [comment]
I will check tomorrow at work.

**Comment by kingaa** [comment]
The issue with the DLL is still troubling me, but the immediate source of the error is clear now.  Try changing your call to the `pomp` constructor to the following:

```
  pomp(
    data = data.frame(
      time=lbv.n[,1],
      DRECJ = lbv.n[,4],
      DRECA = lbv.n[,5],
      DPOPJ = lbv.n[,6],
      DPOPA = lbv.n[,7]
    ),
    times='time',
    t0=0,
    rprocess=euler.sim(step.fun="sir_euler_simulator",delta.t=1),
    rmeasure="binomial_rmeasure",
    dmeasure="binomial_dmeasure",
    statenames=c("SUSJ","MDAJ", "SUSJM","EIJ","ERJ","INFJ", "RECJ", 
"SUSA", "EIA","ERA","INFA", "RECA","SPA","SPJ"),
    states=c("SUSJ","MDAJ", "SUSJM","EIJ","ERJ","INFJ", "RECJ", "SUSA", 
"EIA","ERA","INFA", "RECA","SPA","SPJ"),
    paramnames=c("BETA","RHO","SUSJ.0","MDAJ.0", "SUSJM.0","EIJ.0","ERJ.0",
"INFJ.0", "RECJ.0", "SUSA.0", "EIA.0","ERA.0","INFA.0", "RECA.0","SPA.0","SPJ.0"),
    initializer=function(params,t0,states,...){
      x0<-params[paste(states,".0",sep="")]
      names(x0)<-states
      return(x0)
    }
  ) -> lbvdat
```

The issue is that your `initializer` function needs to know the names of the state variables.  At some point many versions ago, `statenames` became an argument to `pomp` and thus not something that is passed to `initializer`.  In the above, we define `states`.  It gets passed to `initializer` since `pomp` has no other use for it.  See the documentation of the `...` argument in `?pomp`.

You must be using quite an old version of the package.  I'd strongly recommend upgrading to the latest.

**Comment by dtsh2** [comment]
You are right in all cases - 1) the code revisions you put there work, so
thanks. That solves my initial problem. 2) the .dll is an issue. I hadn't
tried recompiling this or if I had I don't recall getting the error.

I will close this issue and take a look at the .c file and see if I can
resolve the compiling issue myself. In the meantime, apologies for the
delayed reply and for not keeping up with pomp versions/material, and
thanks very much for spending the time on this. It is much appreciated.

**Comment by kingaa** [comment]
As you revisit the C code, one word of advice.  I recommend that you use the `Csnippet` facility now provided by **pomp**.  It _should_ make the coding somewhat easier, as it obviates the need for the function and macro declarations.  See the [tutorials](http://kingaa.github.io/pomp/vignettes) for examples, and let me know if you run into problems.  It's through users like you that we build up the documentation and the FAQ to help others in future.
