### ISSUE TITLE
ode_control in traj.match

### ISSUE THREAD

**Issue by 17nak1** [kingaa/pomp#90]
I see in traj.match there is a ode_control optional list that the elements of this list will be passed to deSolve.
How can I change the ode solver method in traj.match?
Right now  I have  `skeleton=vectorfield(modelSnippet_ode)`. Is the default method "lsoda"?

**Comment by kingaa** [comment]
I strongly recommend you switch to using **pomp2**.  Under **pomp2**, the `traj.match` method is replaced by `traj.match.objfun`, which constructs an objective function suitable for use with many different optimizers.  Importantly, this is a *stateful* objective function.  In particular, it remembers the arguments with which it was last called.

Now, to your question.  The elements of the list `ode_control` are passed verbatim to `deSolve::ode`.  By default, yes, `deSolve::ode` uses the `lsoda` solver.  To change the solver, as we see from reading `?ode`, we pass a different option using the `method` argument.  Thus, supposing I have a 'pomp' `P` with a skeleton and a dmeasure, then I can, for example, do
```
traj.match.objfun(P,ode_control=list(method="bdf",hmax=0.1)) -> fn
coef(fn)

library(subplex)
subplex(fn=fn,par=coef(fn))
coef(fn)
```
This will use the "bdf" method to integrate the equations.  Note, I've also fixed the maximum step size here, just to show how other options can be also changed using `ode_control`.

As an aside, note that in order to see all available options, I have to read the documentation for `ode` as well as for the various methods I might choose.  Here, I had a look at `lsode`, which is called by `ode` when `method="bdf"`.

**Comment by 17nak1** [comment]
Thanks for the answer.
I am going to switch using *pomp2* as you recommended. Thank you for your help!
