### ISSUE TITLE
Fitting an age-structured model to a single time series

### ISSUE THREAD

**Issue by caseyzipfel** [kingaa/pomp#93]
Hello!
I was wondering if pomp is able to infer parameters for a multi-layered model (like an age-structured SIR model, for example), with just one set of data. I have seen examples where people use pomp for an age-structured model where they have different sets of infection data for each age group. However, I only have one time series of infection data for the total population that is composed of the various age groups. I have been working with pomp and trying to specify a model that has the different age groups with different contact rates between them, and different interventions applied to different age groups. However, when I look at simulations of the model, I find that my age classes are being equally infected, even though the parameters would lead me to think there would be different levels of infection in the different groups. For example, if there is a higher contact rate within a certain age group, or there is an intervention applied to a certain age group, I would expect the different age groups to have different numbers of infection, but I am finding that my models results in about equal distribution of infection. I am wondering if this is a result of my one infection time series, or if there is something wrong with my model that is causing this.  Thank you!

**Comment by kingaa** [comment]
@caseyzipfel:

There are two issues here.  The first is purely technical: can you implement an age structured model (i.e., one for which the state vector encodes age-structure information), despite the fact that you only have one, aggregated, data variable?  The answer is an unequivocal "Yes".  Nothing stops you in fact from writing an arbitrarily complex unobserved Markov process, regardless of the data you have, or even if you have no data at all.

The second question is practical: "Do my data contain enough information to estimate the structure of the unobserved state process?"  Here, if you have only a single data stream, I am sure you will have little difficulty imagining that you may find it very difficult to distinguish among the many sets of parameters, or even qualitatively distinct model structures, that explain the data equally well, or nearly so.

But you ask a very specific question: "Is there something about having only a single data variable that *forces* the distribution of infection to be equal among ages?"  The answer here is certainly, "No".  I suspect that your codes are not performing as you imagine they should.  Perhaps this is due to a bug in the codes; perhaps it is due to a misunderstanding about the nature of dynamics your model evinces.

I hope this helps.  Without knowing more about what you have done, it is hard for me to offer more.

**Comment by kingaa** [comment]
@caseyzipfel 

I am going to close this issue for now.  If you would like to continue the discussion, feel free to reopen it.
