### ISSUE TITLE
cannot compile shared-object library

### ISSUE THREAD

**Issue by SQ206** [kingaa/pomp#98]
Hello,

I got an error while using pomp.and I tried searching for related content and still couldn't solve it

And I am running pomp v2.4 on a Windows machine with R v3.6.2. Here is the code I used and the error that occurred（Garbled characters appear in the process）：

```
niamey <- read.csv("http://kingaa.github.io/clim-dis/parest/niamey.csv")
ggplot(niamey,mapping=aes(x=biweek,y=measles,color=community))+geom_line()+geom_point()

pomp(
    data=subset(niamey,community=="A",select=-community),
    times="biweek",t0=0,
    skeleton=vectorfield(
     Csnippet("
       DS = -Beta*S*I/N;
       DI = Beta*S*I/N-gamma*I;
       DR = gamma*I;")),
     initializer=Csnippet("
       S = S_0;
       I = I_0;
       R = N-S_0-I_0;"),
     statenames=c("S","I","R"),
     paramnames=c("Beta","gamma","N","S_0","I_0")) -> niameyA
in ‘pomp’: the unrecognized argument ‘initializer’ is available for use by the POMP basic components.
错误: error in building shared-object library from C snippets: in ‘Cbuilder’: compilation error: cannot compile shared-object library ‘C:/Users/user/AppData/Local/Temp/Rtmpiuuscn/2528/pomp_675d572d4cfbf40b5a9042014ab42e78.dll’: status = 1
compiler messages:
Warning messages:
1: In system(cmd) : 'make' not found
2: In system(paste(cmd, "shlib-clean")) : 'make' not found
此外: Warning message:
In system2(command = R.home("bin/R"), args = c("CMD", "SHLIB", "-c",  : 运行命令'"D:/R/R-3.6.2/bin/R" PKG_CPPFLAGS="-ID:/R/R-3.6.2/library/pomp/include -IG:/鑷狢鐩樿浆杞?Documents/R" CMD SHLIB -c -o C:/Users/user/AppData/Local/Temp/Rtmpiuuscn/2528/pomp_675d572d4cfbf40b5a9042014ab42e78.dll C:/Users/user/AppData/Local/Temp/Rtmpiuuscn/2528/pomp_675d572d4cfbf40b5a9042014ab42e78.c'的状态是1
```

**Comment by kingaa** [comment]
There are two problems that you encountered.  The first is due to the fact that there have been substantial changes in **pomp** as of version 2 that break some codes written for earlier versions.  These are all documented in the [pomp version 2 upgrade guide](https://kingaa.github.io/pomp/vignettes/upgrade_guide.html).  In particular, [it is pointed out there](https://kingaa.github.io/pomp/vignettes/upgrade_guide.html#initialization-of-the-latent-state-process) that the `initializer` argument has been replaced by `rinit`.

Thus the following compiles fine for me.
```
library(pomp)

niamey <- read.csv("http://kingaa.github.io/clim-dis/parest/niamey.csv")

pomp(
  data=subset(niamey,community=="A",select=-community),
  times="biweek",t0=0,
  skeleton=vectorfield(
    Csnippet("
         DS = -Beta*S*I/N;
         DI = Beta*S*I/N-gamma*I;
         DR = gamma*I;")
  ),
  rinit=Csnippet("
         S = S_0;
         I = I_0;
         R = N-S_0-I_0;"),
  statenames=c("S","I","R"),
  paramnames=c("Beta","gamma","N","S_0","I_0")
) -> niameyA
```

The other error messages you received suggest that another error lurks just behind the first.  You will need to install **Rtools** on your windows system, as explained in the package installation instructions.

Searching for related content is often a good idea, but there is quite a lot of documentation specific to **pomp** that is available to you.  Do have a look at the package documentation page!

**Comment by SQ206** [comment]
Thank you for your guidance, I will carefully read what you said and learn, thank you again for your help @kingaa

**Comment by SQ206** [comment]
I have successfully solved the above problem. In the process, I used your suggestions and referred to (http://www.freesion.com/article/8282235719/), just install the latest pomp in the windows system. Thank you very much! @kingaa
